#!/usr/bin/env python

import argparse
from distutils.util import strtobool

from cdskit.__init__ import __version__

# Main parser
psr = argparse.ArgumentParser(description='A toolkit for protein-coding DNA sequences in evolutionary biology')
subparsers = psr.add_subparsers()

# Parent parser for shared options
p_parent = argparse.ArgumentParser(add_help=False)
p_parent.add_argument('-s', '--seqfile', metavar='PATH', default='-', type=str, required=False, action='store',
                 help='default=%(default)s: Input sequence file. Use "-" for STDIN.')
p_parent.add_argument('-o', '--outfile', metavar='PATH', default='-', type=str, required=False, action='store',
                 help='default=%(default)s: Output sequence file. Use "-" for STDOUT.')
p_parent.add_argument('-if', '--inseqformat', metavar='STR', default='fasta', type=str, required=False, action='store',
                 help='default=%(default)s: Input sequence format. See Biopython documentation for available options.')
p_parent.add_argument('-of', '--outseqformat', metavar='STR', default='fasta', type=str, required=False, action='store',
                 help='default=%(default)s: Output sequence format. See Biopython documentation for available options.')
p_parent.add_argument('-q', '--quiet', default=False, required=False, action='store_true',
                 help='default=%(default)s: Set this if you do not want progress information from the program.')
p_parent.add_argument('-v', '--verbose', default=False, required=False, action='store_true',
                 help='default=%(default)s: Set this if you want to get more information from the program.')
p_parent.add_argument('--version', action='version', version='cdskit version ' + __version__)

p_codon = argparse.ArgumentParser(add_help=False)
p_codon.add_argument('-d', '--codontable', metavar='INT', default=1, type=int, required=False, action='store',
                      help='default=%(default)s: Codon table ID to be used. '
                           'See here for details: https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi')


def command_accession2fasta(args):
    from cdskit.accession2fasta import accession2fasta_main
    accession2fasta_main(args)

p_accession2fasta = subparsers.add_parser('accession2fasta', help='see `cdskit accession2fasta -h`', parents=[p_parent])
p_accession2fasta.add_argument('--accession_file', metavar='PATH', default='', type=str, required=False, action='store',
                               help='default=%(default)s: PATH to the accession-per-line text file.')
p_accession2fasta.add_argument('--email', metavar='aaa@bbb.com', default='', type=str, required=False, action='store',
                               help='default=%(default)s: Your email address. This is necessary for NCBI\'s E-utilities. '
                                    'For details, see here: https://biopython.org/docs/1.75/api/Bio.Entrez.html')
p_accession2fasta.add_argument('--extract_cds', metavar='yes|no', default='yes', type=strtobool, required=False, action='store',
                               help='default=%(default)s: Whether to extract the CDS feature.')
p_accession2fasta.add_argument('--ncbi_database', metavar='STR', default='nucleotide', type=str, required=False,
                               action='store', choices=['nucleotide', ],
                               help='default=%(default)s: NCBI database to search.')
p_accession2fasta.add_argument('--seqnamefmt', metavar='STR', default='organism_accessions', type=str, required=False, action='store',
                               help='default=%(default)s: Underline-separated list of sequence name elements.')
p_accession2fasta.set_defaults(handler=command_accession2fasta)


def command_aggregate(args):
    from cdskit.aggregate import aggregate_main
    aggregate_main(args)

p_aggregate = subparsers.add_parser('aggregate', help='see `cdskit aggregate -h`', parents=[p_parent])
p_aggregate.add_argument('-m', '--mode', metavar='STR', default='longest', type=str, required=False, action='store',
                         choices=['longest', ],
                         help='default=%(default)s: Criterion to keep a sequence during aggregation.')
p_aggregate.add_argument('-x', '--expression', metavar='REGEX', default='-', type=str, required=False, action='store',
                         nargs='+',
                         help='default=%(default)s: A regular expression to aggregate the sequences. Multiple values can be specified.')
p_aggregate.set_defaults(handler=command_aggregate)


def command_backtrim(args):
    from cdskit.backtrim import backtrim_main
    backtrim_main(args)

p_backtrim = subparsers.add_parser('backtrim', help='see `cdskit backtrim -h`', parents=[p_parent,p_codon])
p_backtrim.add_argument('-a', '--trimmed_aa_aln', metavar='PATH', default='', type=str, required=True, action='store',
                        help='default=%(default)s: PATH to the trimmed amino acid alignment. '
                             'In addition to this, please specify the untrimmed CDS alignment by --seqfile.')
p_backtrim.set_defaults(handler=command_backtrim)


def command_parsegb(args):
    from cdskit.parsegb import parsegb_main
    parsegb_main(args)

p_parsegb = subparsers.add_parser('parsegb', help='see `cdskit parsegb -h`', parents=[p_parent])
p_parsegb.add_argument('--seqnamefmt', metavar='STR', default='organism_accessions', type=str, required=False, action='store',
                             help='default=%(default)s: Underline-separated list of sequence name elements.')
p_parsegb.add_argument('--extract_cds', metavar='yes|no', default='yes', type=strtobool, required=False, action='store',
                       help='default=%(default)s: Whether to extract the CDS feature.')
p_parsegb.set_defaults(handler=command_parsegb)


def command_hammer(args):
    from cdskit.hammer import hammer_main
    hammer_main(args)

p_hammer = subparsers.add_parser('hammer', help='see `cdskit hammer -h`', parents=[p_parent,p_codon])
p_hammer.add_argument('--nail', metavar='INT/all', default='4', type=str, required=False, action='store',
                      help='default=%(default)s: Threshold number of "nail sequences" to hammer down. '
                           'Codons are removed if there are no more than this number of non-missing sequences. '
                           'e.g., For meaningful analysis of molecular convergence, this value should be 4 or more. '
                           'Specifying "all" sets it to the number of input sequences and produces no-gap outputs.')
p_hammer.add_argument('--prevent_gap_only', metavar='yes|no', default='yes', type=strtobool, required=False, action='store',
                       help='default=%(default)s: Whether to decrease --nail when gap-only sequences are generated.')
p_hammer.set_defaults(handler=command_hammer)


def command_mask(args):
    from cdskit.mask import mask_main
    mask_main(args)

p_mask = subparsers.add_parser('mask', help='see `cdskit mask -h`', parents=[p_parent,p_codon])
p_mask.add_argument('-c', '--maskchar', metavar='CHAR', default='N', type=str, required=False, action='store',
                    choices=['N', '-'],
                    help='default=%(default)s: A character to be used to mask codons.')
p_mask.add_argument('-a', '--ambiguouscodon', metavar='yes|no', default='yes', type=str, required=False, action='store',
                    choices=['yes', 'no'],
                    help='default=%(default)s: Mask ambiguous codons.')
p_mask.add_argument('-t', '--stopcodon', metavar='yes|no', default='yes', type=str, required=False, action='store',
                    choices=['yes', 'no'],
                    help='default=%(default)s: Mask stop codons.')
p_mask.set_defaults(handler=command_mask)


def command_pad(args):
    from cdskit.pad import pad_main
    pad_main(args)

p_pad = subparsers.add_parser('pad', help='see `cdskit pad -h`', parents=[p_parent,p_codon])
p_pad.add_argument('-c', '--padchar', metavar='CHAR', default='N', type=str, required=False, action='store',
                   choices=['N', '-'],
                   help='default=%(default)s: A character to be used to pad when the sequence length is not multiple of three.')
p_pad.add_argument('-n', '--nopseudo', default=False, required=False, action='store_true',
                   help='default=%(default)s: Drop sequences that contain stop codon(s) even after padding to 5\'- or 3\'- terminal.')
p_pad.set_defaults(handler=command_pad)


def command_printseq(args):
    from cdskit.printseq import printseq_main
    printseq_main(args)

p_printseq = subparsers.add_parser('printseq', help='see `cdskit printseq -h`', parents=[p_parent,p_codon])
p_printseq.add_argument('-n', '--seqname', default='', type=str, required=False, action='store',
                        help='default=%(default)s: Name of the sequence to print. Regex is supported.')
p_printseq.add_argument('--show_seqname', metavar='yes|no', default='yes', type=strtobool, required=False, action='store',
                        help='default=%(default)s: Whether to show sequence name starting with ">".')
p_printseq.set_defaults(handler=command_printseq)

def command_rmseq(args):
    from cdskit.rmseq import rmseq_main
    rmseq_main(args)

p_rmseq = subparsers.add_parser('rmseq', help='see `cdskit rmseq -h`', parents=[p_parent,p_codon])
p_rmseq.add_argument('--seqname', default='', type=str, required=False, action='store',
                        help='default=%(default)s: Names of sequences to remove. Regex is supported.')
p_rmseq.add_argument('--problematic_char', default='NX-?', type=str, required=False, action='store',
                        help='default=%(default)s: Problematic characters considered by --problematic_percent. Without separator.')
p_rmseq.add_argument('--problematic_percent', default=0, type=float, required=False, action='store',
                        help='default=%(default)s: Sequences containing >= this percentage of --problematic_char are removed.')
p_rmseq.set_defaults(handler=command_rmseq)

def command_stats(args):
    from cdskit.stats import stats_main
    stats_main(args)

p_stats = subparsers.add_parser('stats', help='see `cdskit stats -h`', parents=[p_parent])
p_stats.set_defaults(handler=command_stats)


# Handler
args = psr.parse_args()
if hasattr(args, 'handler'):
    args.handler(args)
else:
    psr.print_help()
